version: '3'
services:
  app:
    build: .
    ports:
      - "8014:8014"
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:5.0.15"
    volumes:
      - "mongodb_data:/data/db"
volumes:
  mongodb_data:
